feat: default mise, taskfile instead of extension

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -6,18 +6,26 @@ on:
       upload-artifacts:
         type: boolean
         default: false
-      working-directory:
-        type: string
-        default: "."
 
 jobs:
   ci:
     runs-on: ubuntu-latest
-    defaults:
-      run:
-        working-directory: ${{ inputs.working-directory }}
     steps:
       - uses: actions/checkout@v4
+
+      - name: check if Taskfile exists
+        run: |
+          if [ ! -f "Taskfile.yml" ]; then
+            echo "Taskfile.yml not found. Please create one in the root of the repository."
+            exit 1
+          fi
+
+      - name: check if mise.toml exists
+        run: |
+          if [ ! -f "mise.toml" ]; then
+            echo "mise.toml not found. Please create one in the root of the repository."
+            exit 1
+          fi
 
       - uses: jdx/mise-action@v3
         with:
@@ -46,6 +54,9 @@ jobs:
       - name: run lint
         run: task lint
 
+      - name: run build
+        run: task build
+
       - name: run tests
         run: task test:ci
 
@@ -54,7 +65,7 @@ jobs:
         uses: actions/upload-artifact@v4
         with:
           name: test-results
-          path: ${{ inputs.working-directory }}/reports/junit.xml
+          path: reports/junit.xml
 
       - name: run vulnerability scan
         run: task vuln:ci
